version: '3.7'

volumes:
  postgres_data:
      driver: local

services:
  postgres:
      image: postgres
      container_name: postgresKeycloak
      restart: unless-stopped
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: <username>
        POSTGRES_USER: <username>
        POSTGRES_PASSWORD: <password>
  
  keycloak:
      image: jboss/keycloak
      container_name: keycloak
      restart: unless-stopped
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: <password>
        DB_USER: <username>
        DB_PASSWORD: password
        KEYCLOAK_USER: <username>
        KEYCLOAK_PASSWORD: <password>
      volumes:
        - ./apps/:/opt/jboss/keycloak/docs/examples/unconfigured-demo/
      ports:
        - 8081:8080
      depends_on:
        - postgres
