version: '3.7'

services:
  pgadmin:
    container_name: postgresTP
    image: postgres
    restart: unless-stopped
    hostname: localhost
    environment:
        - POSTGRES_USER=<username>
        - POSTGRES_PASSWORD=<password>
    ports:
        - 5432:5432
